# Generated by Django 4.2.4 on 2023-08-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home_values',
            new_name='HomeFields',
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='HomeSection',
        ),
    ]
