# Generated by Django 4.2.4 on 2023-08-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_acount_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
