# Generated by Django 4.2.4 on 2023-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_turn_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
