# Generated by Django 4.2.4 on 2023-08-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('agenda', '0005_manager_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
