# Generated by Django 4.2.4 on 2023-08-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_turn_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager_turn',
        ),
    ]
