# Generated by Django 4.2.4 on 2023-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesession',
            name='name',
            field=models.CharField(default='nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typesession',
            name='in_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typesession',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typesession',
            name='social_rounds',
            field=models.BooleanField(default=False),
        ),
    ]
