# Generated by Django 4.2.4 on 2023-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_typesession_name_alter_typesession_in_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesession',
            name='name',
            field=models.CharField(default='nombre', max_length=50),
        ),
    ]
