# Generated by Django 4.2.4 on 2023-08-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_values',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
