# Generated by Django 4.2.4 on 2023-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
