# Generated by Django 4.2.4 on 2023-08-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_acount_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='imgAvatar',
            field=models.ImageField(default='/media/avatares/avatar.png', upload_to='avatares'),
        ),
    ]
